SET SERVEROUTPUT ON;

DECLARE
    PROCEDURE crear_tabla(
        p_nombre_tabla IN VARCHAR2,
        p_sentencia    IN VARCHAR2
    ) IS
        v_cantidad NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO v_cantidad
          FROM USER_TABLES
         WHERE TABLE_NAME = UPPER(p_nombre_tabla);

        IF v_cantidad = 0 THEN
            EXECUTE IMMEDIATE p_sentencia;
            DBMS_OUTPUT.PUT_LINE('Tabla creada: ' || p_nombre_tabla);
        ELSE
            DBMS_OUTPUT.PUT_LINE('Tabla existente: ' || p_nombre_tabla);
        END IF;
    END crear_tabla;
BEGIN
    crear_tabla(
        'USUARIOS',
        q'~
            CREATE TABLE usuarios (
                id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                nombre      VARCHAR2(255 CHAR),
                correo      VARCHAR2(255 CHAR),
                contrasena  VARCHAR2(255 CHAR),
                rol         VARCHAR2(255 CHAR),
                CONSTRAINT pk_usuarios PRIMARY KEY (id)
            )
        ~'
    );

    crear_tabla(
        'CURSOS',
        q'~
            CREATE TABLE cursos (
                id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                nombre      VARCHAR2(255 CHAR) NOT NULL,
                instructor  VARCHAR2(255 CHAR) NOT NULL,
                duracion    VARCHAR2(255 CHAR) NOT NULL,
                costo       NUMBER(10,2) NOT NULL,
                CONSTRAINT pk_cursos PRIMARY KEY (id)
            )
        ~'
    );

    crear_tabla(
        'INSCRIPCIONES',
        q'~
            CREATE TABLE inscripciones (
                id                 NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                estudiante_id      NUMBER(19,0) NOT NULL,
                fecha_inscripcion  DATE NOT NULL,
                total              NUMBER(10,2) NOT NULL,
                metodo_pago        VARCHAR2(255 CHAR) NOT NULL,
                estado_pago        VARCHAR2(255 CHAR) NOT NULL,
                CONSTRAINT pk_inscripciones PRIMARY KEY (id)
            )
        ~'
    );

    crear_tabla(
        'INSCRIPCION_CURSOS',
        q'~
            CREATE TABLE inscripcion_cursos (
                id              NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                inscripcion_id  NUMBER(19,0) NOT NULL,
                curso_id        NUMBER(19,0) NOT NULL,
                nombre_curso    VARCHAR2(255 CHAR) NOT NULL,
                costo_curso     NUMBER(10,2) NOT NULL,
                CONSTRAINT pk_inscripcion_cursos PRIMARY KEY (id)
            )
        ~'
    );

    crear_tabla(
        'EVALUACIONES',
        q'~
            CREATE TABLE evaluaciones (
                id                NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                curso_id          NUMBER(19,0),
                nombre            VARCHAR2(255 CHAR),
                puntaje_maximo    NUMBER(10,0) NOT NULL,
                fecha_aplicacion  DATE,
                CONSTRAINT pk_evaluaciones PRIMARY KEY (id)
            )
        ~'
    );

    crear_tabla(
        'PAGOS',
        q'~
            CREATE TABLE pagos (
                id              NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                inscripcion_id  NUMBER(19,0) NOT NULL,
                monto           NUMBER(10,2) NOT NULL,
                metodo_pago     VARCHAR2(255 CHAR) NOT NULL,
                estado          VARCHAR2(255 CHAR) NOT NULL,
                fecha_pago      TIMESTAMP(6) NOT NULL,
                CONSTRAINT pk_pagos PRIMARY KEY (id)
            )
        ~'
    );

    crear_tabla(
        'NOTIFICACION',
        q'~
            CREATE TABLE notificacion (
                id              NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                usuario_id      NUMBER(19,0),
                titulo          VARCHAR2(255 CHAR),
                mensaje         VARCHAR2(255 CHAR),
                tipo            VARCHAR2(255 CHAR),
                leida           NUMBER(1,0),
                fecha_creacion  TIMESTAMP(6),
                CONSTRAINT pk_notificacion PRIMARY KEY (id),
                CONSTRAINT ck_notificacion_leida
                    CHECK (leida IS NULL OR leida IN (0, 1))
            )
        ~'
    );

    crear_tabla(
        'RESUMEN_COMPRA_MQ',
        q'~
            CREATE TABLE RESUMEN_COMPRA_MQ (
                ID                 NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                INSCRIPCION_ID     NUMBER(19,0) NOT NULL,
                ESTUDIANTE_ID      NUMBER(19,0) NOT NULL,
                NUMERO_RESUMEN     VARCHAR2(50 CHAR) NOT NULL,
                FECHA_INSCRIPCION  TIMESTAMP(6),
                TOTAL              NUMBER(12,2) NOT NULL,
                METODO_PAGO        VARCHAR2(50 CHAR) NOT NULL,
                ESTADO_PAGO        VARCHAR2(50 CHAR) NOT NULL,
                CONTENIDO_JSON     CLOB,
                FECHA_GUARDADO     TIMESTAMP(6) NOT NULL,
                CONSTRAINT pk_resumen_compra_mq PRIMARY KEY (ID)
            )
        ~'
    );
END;
/

COMMIT;