server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ENTRA_ISSUER_URI:https://login.microsoftonline.com/0bca00cb-b642-4823-b0d8-b4435e501b77/v2.0}
          audiences:
            - "${ENTRA_API_CLIENT_ID:5353f5c6-49a7-45f2-a25f-b77bb6bacf83}"

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: bff-service
              uri: ${BFF_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/bff/**

            - id: usuarios-service
              uri: ${BACKEND_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/usuarios/**

            - id: cursos-service
              uri: ${CURSOS_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/cursos/**

            - id: inscripciones-service
              uri: ${BACKEND_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/inscripciones/**

            - id: evaluaciones-service
              uri: ${BACKEND_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/evaluaciones/**

            - id: pagos-service
              uri: ${BACKEND_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/pagos/**

            - id: notificaciones-service
              uri: ${BACKEND_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/notificaciones/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always