spring.application.name=inscripciones-service
server.port=${SERVER_PORT:8081}

# Conexion Oracle Autonomous Database con TLS
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:oracle.jdbc.OracleDriver}

# Configuracion JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.OracleDialect}

# AWS S3
aws.s3.bucket=${AWS_S3_BUCKET}
aws.region=${AWS_REGION}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Comunicacion con microservicios
services.cursos.url=${CURSOS_SERVICE_URL:http://localhost:8082}

# IDaaS / Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=${IDP_ISSUER_URI:http://localhost:9090/realms/plataforma-educativa}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${IDP_JWK_SET_URI:http://localhost:9090/realms/plataforma-educativa/protocol/openid-connect/certs}

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}

# MQ - Resumen de inscripcion
app.mq.inscripcion.exchange=inscripciones.exchange
app.mq.inscripcion.queue=inscripciones.resumen.queue
app.mq.inscripcion.routing-key=inscripcion.resumen.creado