spring.application.name=inscripciones-service
server.port=8081

# Conexion Oracle Autonomous Database con TLS
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:oracle.jdbc.OracleDriver}

# Configuracion JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.OracleDialect}

# AWS S3
aws.s3.bucket=${AWS_S3_BUCKET}
aws.region=${AWS_REGION}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# IDaaS / Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=${IDP_ISSUER_URI:http://localhost:9090/realms/plataforma-educativa}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${IDP_JWK_SET_URI:http://localhost:9090/realms/plataforma-educativa/protocol/openid-connect/certs}
