spring.application.name=curso-service
server.port=${SERVER_PORT:8082}

# Conexion Oracle Autonomous Database con TLS
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:oracle.jdbc.OracleDriver}

# Configuracion JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.OracleDialect}
spring.jpa.open-in-view=false

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always